global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "observability-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
