groups:
- name: observability-app-alerts
  rules:
  - alert: HighHttp500ErrorCount
    expr: increase(app_http_requests_total{status="500"}[2m]) > 20
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "High number of HTTP 500 errors"
      description: "More than 20 HTTP 500 errors occurred in the last 2 minutes."
